export const DEFAULT_MESSAGES = [
  '¡Vamos, hoy es otro paso hacia tu meta! 🚀',
  'El conocimiento es poder, y tú estás construyendo el tuyo. 💡',
  'Cada minuto de estudio te acerca más a tus sueños. 🌟',
  'La constancia es la clave del éxito. ¡Sigue adelante! 💪',
  'Tu futuro yo te agradecerá el esfuerzo de hoy. 💖',
  'No hay atajos hacia ningún lugar que valga la pena ir. 💡',
  'El aprendizaje nunca agota la mente. ¡Continúa! 💡',
  'Eres más fuerte de lo que crees y más capaz de lo que imaginas. 💪',
  'Cada sesión de estudio es una inversión en ti mismo. 💪',
  'La disciplina es el puente entre metas y logros. 💪',
  '¡Hoy es un gran día para aprender algo nuevo! 💡',
  'Tu dedicación de hoy será tu éxito de mañana. 💪',
  'El progreso, no la perfección, es lo que importa. 💡',
  'Confía en el proceso y disfruta el viaje del aprendizaje. 💡',
  '¡Estás creando la versión más inteligente de ti mismo! 💪',
  'La mente es como un paracaídas, solo funciona cuando está abierta. 🧠',
  'Cada error es una oportunidad de aprender algo nuevo. 📚',
  'El éxito no es final, el fracaso no es fatal: lo que cuenta es el coraje para continuar. 🎯',
  'Tu actitud determina tu altitud en el aprendizaje. ✨',
  'El tiempo que dedicas a estudiar es tiempo que inviertes en tu futuro brillante. ⏰',
  'La curiosidad es la chispa que enciende la llama del conocimiento. 🔥',
  'Cada día es una nueva oportunidad para ser mejor que ayer. 🌅',
  'El aprendizaje es un tesoro que te acompañará toda la vida. 💎',
  'La perseverancia convierte los sueños imposibles en realidades alcanzables. 🌈',
  'Tu potencial es ilimitado, solo necesitas creer en ti mismo. ⭐',
  'El conocimiento es la mejor inversión que puedes hacer en ti mismo. 📈',
]
